IF NOT EXISTS(select * from sys.tables where name = 'TB_LIVROS')
BEGIN
	CREATE TABLE TB_LIVROS
	(
		 Id INT PRIMARY KEY IDENTITY(1,1)
		,Nome VARCHAR(100) NOT NULL
		,Categoria VARCHAR(100) NOT NULL DEFAULT('NÃO IDENTIFICADO')
		,Preco FLOAT NOT NULL	
	)	
END
GO